spring:
  datasource:
    url: jdbc:mysql://mysql-service-db:3306/meli
    username: user
    password: Espinosa2010
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

resilience4j:
  circuitbreaker:
    instances:
      countryService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

endpoint-service:
  ip-service:
    url: http://api.ipapi.com/%s?access_key=ecbf8e62b479066c40adf804df32d0d5
  country-service:
    url: https://free.currconv.com/api/v7/countries?apiKey=906aa577080d905adb80
  currency-conversion-service:
    url: https://free.currconv.com/api/v7/convert?q=%s&compact=ultra&apiKey=906aa577080d905adb80
